CREATE DATABASE SalveFocinhos;

use SalveFocinhos;

CREATE TABLE usuarios(
	id INT PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	telefone VARCHAR(255) NOT NULL,
	senha VARCHAR(255) NOT NULL,
	ft_perfil VARCHAR(255)
);